server:
  error:
    include-message: always

spring:
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    hikari:
      maximumPoolSize: 1
      data-source-properties:
        preparedStatementCacheQueries: 0
      allow-pool-suspension: true
  threads:
    virtual:
      enabled: true

# Camel specific properties
camel:
  main:
    name: camel-application
    tracing: false
  component:
    cenas:
      enabled: true
      timer:
        interval: 10000
    http:
      enabled: true

management:
  endpoint:
    health:
      probes:
        enabled: true
    camelroutes:
      read-only: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: camelroutes,health,info
  server:
    port: 8381
  security:
    enabled: false
